Add internet permission to manifest
This gives our app access (or the right to) Internet. If not specified in the manifest, a security
exception is generated a run-time:
java.lang.SecurityException: Permission denied (missing INTERNET permission?)